name: getx_project
version: 1.0.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: ^2.0.3
  json_annotation: ^4.6.0
  dio: ^4.0.6
  chopper: ^4.0.6
  chucker_flutter: ^1.3.4
  logger: ^1.1.0
  flutter_native_splash: ^2.2.6
  flutter_launcher_icons: ^0.9.3
  settings_ui: ^2.0.2
  adaptive_dialog: ^1.7.0
  cached_network_image: ^3.2.1
  # flutter_blurhash: ^0.7.0
  lottie: ^1.4.1
  introduction_screen: ^3.0.2
  modal_bottom_sheet: ^2.1.0
  just_audio: ^0.9.28
  better_player: ^0.0.83 # recommanded
  chewie: ^1.3.4
  video_player: ^2.4.5
  audio_video_progress_bar: ^0.10.0
  flutter_login: ^4.0.0
  carousel_slider: ^4.1.1
  flutter_slidable: ^2.0.0
  infinite_scroll_pagination: ^3.2.0
  # drift: ^1.7.1
  # sqlite3_flutter_libs: ^0.5.9
  # path_provider: ^2.0.11 # getting commonly directories
  # path: ^1.8.1 # path operations
  # file_picker: ^5.2.0
  image_picker: ^0.8.5
  flutter_local_notifications: ^9.7.0
  awesome_notifications: ^0.6.21
  # qr_code_scanner: ^1.0.0 # requires Android SDK version 32
  share_plus: ^4.0.10
  package_info_plus: ^1.4.3
  # font_awesome_flutter: ^10.1.0
  appwrite: ^8.1.0
  device_preview: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  drift_dev: ^1.7.0
  chopper_generator: ^4.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lottiefiles/
    - assets/videos/

flutter_icons:
  image_path: "assets/flutter.png"
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
